[package]
name = "mddf"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15.7"
fantoccini = "0.21.4"
image = "0.25.5"
pdf-writer = "0.12.0"
reqwest = "0.12.12"
scraper = "0.22.0"
tokio = "1.42.0"
